### ISSUE TITLE
dependent BAP version is master

### ISSUE THREAD

**Issue by jishoon** [draperlaboratory/cbat_tools#103]
I tried to install `cbat_value_set` pass on ubuntu 18.04 with BAP 2.0.0. And It fails with dependency problem.

```
Installing /home/hulk/.opam/4.07.0/lib/cbat_value_set/opam
opam pin add -y .
Package cbat_value_set does not exist, create as a NEW package? [Y/n] y
[cbat_value_set.~dev] synchronised from file:///home/hulk/code/bap/cbat_tools/value_set/lib
cbat_value_set is now pinned to file:///home/hulk/code/bap/cbat_tools/value_set/lib (version 0.1)
The following dependencies couldn't be met:
  - cbat_value_set → bap >= master
      no matching version

[NOTE] Pinning command successful, but your installed packages may be out of sync.
$ bap --version
2.0.0
```

The version of dependent BAP is `master`. It was failed because my BAP wasn't built from the master repository. I could successfully installed `cbat_value_set` by replacing `master` to `2.0.0`.

Should BAP version be `master`? If not, It is better to fill with actual version number.

**Comment by codyroux** [comment]
Hi @jishoon, sorry for the late response! We've created a "release" branch, which depends on bap 2.0.0, and should be suitable for your purposes. Please tell us if you run into further trouble.

The master branch is being used for development, so we're sticking to depending on BAP master for the moment, since some of our features are somewhat experimental.
