### ISSUE TITLE
rebuild plugin upon library changes

### ISSUE THREAD

**Issue by DieracDelta** [draperlaboratory/cbat_tools#252]
Based on [this](https://github.com/ocaml/ocamlbuild/issues/221), when a library dependency to a binary is updated, the binary is not relinked to support the new library. The solution here is, when the plugin is changed, to `clean` the plugin directory, then rebuild. This forces linking to the new version of the library. To accomplish this, we can watch the library from the root makefile, and on a change to that file, `-clean` the plugin before rebuilding.

**Comment by DieracDelta** [comment]
[This](https://github.com/DieracDelta/cbat_tools/commit/e0bd9fc55407cf2d97fbbb9543aecca766f70502) may be a fix. It adds in a an extra file under `_build` in the plugin folder that `make` tracks. Then when any of the library files have been modified after this extra file, `bapbuild -clean` is run. I'm not sure if this is the most idiomatic solution, but it seems to work (if just as a temporary fix). If this seems reasonable, I can open a PR.

I had initially wanted to use the version of the installed library, but that gets written to each time since currently invoking `make` always reinstalls the library.

**Comment by jtpaasch** [comment]
Off the top of my head, I don't think I have any objections to this.

The problem you're trying to solve is a problem caused by `ocamlbuild`, rather than from something we're doing. So really it's `ocamlbuild` that's forcing us to either (i) reinstall every time (which seems rather contrary to the whole point of `make`), or (ii) find some other solution.

This seems like a simple and clean way of accomplishing (ii). It's just a humble file, which doesn't intrude upon any of the other workings of anything. It can be removed easily if we ever get a better solution. Anybody else have any thoughts?

**Comment by fortunac** [comment]
I also have no objections! The change is very clean, and easy to read too.

**Comment by DieracDelta** [comment]
closed with #255
