### ISSUE TITLE
Update all plugins to BAP 2.0

### ISSUE THREAD

**Issue by codyroux** [draperlaboratory/cbat_tools#58]
Not sure what's required for this one, hopefully no too much except the `BitVector` module.

It also sounds like they're moving away from having, for every module `M`, a sub-module `M.Set` and `M.Map`, which I use *extensively* in WP, so maybe some re-factoring there as well.

**Comment by ivg** [comment]
Nothing is required, the Bap.Std interface is backward compatible. It would be good to eventually update cbat_tools to use the more general Bap 2.0 interfaces (i.e., Bap_core_theory and Bap_knowledge) and make VSA available in the knowledge base. But this is not immediately required. Again, old analysis will continue to work for the observed future, it just won't be able to benefit from all the new features. 

> It also sounds like they're moving away from having, for every module M, a sub-module M.Set and M.Map, which I use extensively in WP, so maybe some re-factoring there as well.

Well, our new modules are not exposing those interfaces (old are still having the same interface), but Base/Core_kernel is making the obsolete, so expect them to disappear from Base/Core_kernel sooner or later. The change is easy, instead of `M.Map` one should use just `Map` :)

**Comment by ivg** [comment]
I've recalled one semantic change that might affect you. When we reify program semantics into BIR we no longer create the `ret` terms. Now BAP 2.x you won't have any `return dst` terms, instead it will be reified to a more general `call dst with noreturn`, where `dst` is some expression denoting the set of possible return destinations. 

Do you think it will affect you?

**Comment by codyroux** [comment]
It might affect us, but I think we can handle it! Thanks again.

**Comment by fortunac** [comment]
Handled in #65
